name: music-production
favicon: null
layout_spectrum: 1
typography_spectrum: 0.89179
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4688f1'
    - '#454545'
    - '#e7453c'
    - '#f9bb2d'
  brandStrength: 0.75
  lightness: 0.26152344211004674
  saturation: 0.824653506744653
  rhythmicContrast: 0.8292071667965502
purpose: []
